version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3-stretch
    steps:
      - checkout
      - run: npm install
      - run: npx lerna bootstrap
      - run: npx lerna run test
